package pl.edu.amu.wmi;


import com.google.common.cache.CacheBuilder;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class LibraryA {
    public boolean someLibraryMethod() {
        CacheBuilder.newBuilder();
        return true;
    }
}
